import type { Metadata } from "next";
import { Nunito, Josefin_Sans } from "next/font/google";
import "./globals.css";
import Header from "./Components/Header";
import Footer from "./Components/Footer";
import { Toaster } from "react-hot-toast";

const nunito = Nunito({ subsets: ["latin"] });
const josefin = Josefin_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Easy Sell Products",
    description: "Easy Sell Products Generated by create next app",
    openGraph: {
        images: [
            `https://ecommerce-nextjs-supabase.vercel.app/assets/sellProducts.png`,
        ],
    },
    alternates: {
        canonical: "https://ecommerce-nextjs-supabase.vercel.app",
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" data-theme="bumblebee">
            <body className={nunito.className}>
                <Toaster />
                <Header font={josefin.className} />
                <main className="py-[2vh] px-[4vh] min-h-screen">
                    {children}
                </main>
                <Footer font={josefin.className} />
            </body>
        </html>
    );
}
